apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-crud-app-config
  namespace: default
data:
  FLASK_ENV: "production"
  FLASK_DEBUG: "false"
  WORKERS: "4"
  WORKER_CLASS: "sync"
  WORKER_TIMEOUT: "60"
