apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-crud-app
  namespace: default
  labels:
    app: flask-crud-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - flask-app.example.com
    secretName: flask-crud-app-tls
  rules:
  - host: flask-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-crud-app
            port:
              number: 80
